# Generated by Django 3.1.2 on 2020-11-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='height',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='car',
            name='width',
            field=models.IntegerField(default=200),
        ),
    ]
