# Generated by Django 3.1.2 on 2020-11-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20201103_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='height',
            new_name='length',
        ),
    ]
